### ISSUE TITLE
Package size too large

### ISSUE THREAD

**Issue by lassoan** [Auditory-Biophysics-Lab/Slicer-ABLTemporalBoneSegmentation#2]
The extension package size is over 150MB due to bundling two huge data files: https://github.com/Auditory-Biophysics-Lab/Slicer-ABLTemporalBoneSegmentation/blob/55e4155b904e2851b347da9ea39c9074073c60ac/ABLTemporalBoneSegmentationModule/CMakeLists.txt#L11-L12

This causes huge unnecessary storage burden (new package is created on 3 platforms for preview and stable release, resulting in almost 1GB extra storage increase per day). Please update the ABLTemporalBoneSegmentationModule so that it downloads the atlas files at runtime. You can find here examples about how to load an image from a URL: https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#Load_volume_from_URL. The downloaded data is cached and shared between all Slicer installations of the user.

**Comment by DoctorSelar** [comment]
Sorry about that! This should be fixed now; please let me know if it isn't.

**Comment by lassoan** [comment]
Instead of downloading from an old git commit, I would recommend to upload the atlas files as a release asset in a Release you create in this repository. It allows you to have a small repository and you can easily upload additional atlases later.

Note that you need to remove reference to the mha files (that don't exist anymore in current version in the repository) from the package, as currently there is a configuration error. - http://slicer.cdash.org/viewBuildError.php?buildid=2000816

**Comment by DoctorSelar** [comment]
Thanks! I've resolved this and removed a number of other large files kicking around in very early commits.
